from enum import Enum

class Tokens(Enum):
	NEWLINE, MNEMONIC, DEFINE, IDENTIFIER, SPACES, HASH, CONSTANT, X_INDEX, Y_INDEX, COLON, LEFT_BRACKET, RIGHT_BRACKET, COMMENT, BAD_TOKEN, \
	IMMEDIATE, NO_PARAM, ONE_PARAM, LABEL, X_INDIRECT, INDIRECT_Y, \
	RELATIVE, ABSOLUTE, ABSOLUTE_X, ABSOLUTE_Y, ZERO, ZERO_X, ZERO_Y, INDIRECT = range(28)

	def __repr__(self):
		return self.name
